words = ["Sliwki",
        "Marchewki",
        "Brokuly",
        "Pomidory",
        "Jablka",
        "Drzewa",
        "Krzaki",
        "Liscie",
        "Trawa",
        "Owoce",
        "Warzywa"]