# Generated by Django 3.2.6 on 2021-09-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_istrue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isTrue',
            field=models.BooleanField(default=True),
        ),
    ]
